name: Release Latest

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release_latest:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: package
        run: mvn clean package -Dmaven.test.skip=true
      - name: rename jar
        run: mv target/coap-simulator-0.0.1-SNAPSHOT-jar-with-dependencies.jar coap-simulator.jar
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest

      # Creates the new release with the binary as a release asset.
      # If the previous Action was skipped, then this keeps the same tag as the
      # previous release.
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "latest jar"
          draft: false
          name: "latest jar"
          tag_name: latest
          files: coap-simulator.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
